### ISSUE TITLE
Issue with 'Submit for Review' button using Wagtail-Review (0.3.1) when used with Wagtail (4.1.2) 

### ISSUE THREAD

**Issue by SenorRude** [wagtail/wagtail-review#50]
After clicking on the "Submit for Review " button it stays greyed out and we get a console error.  Any clues on why this is happening?  Any tips on how to resolve?

The console log error message I see in Chrome dev tools is related to a Uncaught Syntax Error: Unexpected toke '<', <!doctype "... is not valid JSON related to modal-workform.js.

**Comment by gasman** [comment]
Thanks for the report! This has now been fixed in #52 and released as part of version 0.4.
