### ISSUE TITLE
register_page_action_menu_item hook

### ISSUE THREAD

**Issue by AdrienLemaire** [wagtail/wagtail-review#8]
While reading your code, I found about the `wagtail_hooks.HAS_ACTION_MENU_HOOK` var, and just wanted to mention that the [register_page_action_menu_item hook](https://github.com/wagtail/wagtail/pull/4781/files) was merged in November 2018 and is available in recent versions of wagtail :)

Thanks for making this plugin, I'm learning a lot from it.  I wish the core wagtail was also using swapper :)

**Comment by gasman** [comment]
Updated in ddc221fcaeb63ec26cd3dde860d76c5a3c7ee717 (and support for older Wagtail versions without the hook dropped in 91dbd2dfebe5d72417f01c004d3a93082cf238e0). Thanks!
